[build]
  publish = "."
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/namaz-guide-assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
